Repository Capgemini/dcx-react-library, pull requests merged in 2023-06, with the labels that each got.

#495 create a list component
  .storybook/preview.js
  example/src/components/ListDemo.tsx
  example/src/components/index.ts
  example/src/index.tsx
  example/src/pages/HomePage.tsx
  src/index.ts
  src/list/List.tsx
  src/list/ListItem.tsx
  src/list/UseList.tsx
  src/list/__test__/List.test.tsx
  src/list/__test__/ListItem.test.tsx
  src/list/index.ts
  stories/List/Classbased.stories.js
  stories/List/Documentation.mdx
  stories/List/Live.stories.js
  stories/List/UnStyled.stories.js
  stories/List/style.css
  stories/govUkStyle.css
  stories/liveEdit/ListLive.tsx
Labels: new component, ready to merge, typography

#510 expose and document the hook useHydrated
  src/common/utils/__tests__/clientOnly.test.tsx
  src/common/utils/clientOnly.tsx
  stories/Utils/Documentation-server.stories.mdx
Labels: documentation, Comments to be solved

#509 Highlight Component
  .storybook/preview.js
  src/highlight/Highlight.tsx
  src/highlight/__tests__/Highlight.test.tsx
  src/highlight/index.ts
  stories/Highlight/ClassBased.stories.js
  stories/Highlight/Documentation.mdx
  stories/Highlight/Live.stories.js
  stories/Highlight/UnStyled.stories.js
  stories/Highlight/style.css
  stories/liveEdit/HighlightLive.tsx
Labels: new component, typography

#512 feature/abbreviate
  .storybook/preview.js
  src/abbreviate/Abbreviate.tsx
  src/abbreviate/__tests__/Abbreviate.test.tsx
  src/abbreviate/index.ts
  stories/Abbreviate/ClassBased.stories.js
  stories/Abbreviate/Documentation.mdx
  stories/Abbreviate/Live.stories.js
  stories/Abbreviate/UnStyled.stories.js
  stories/Abbreviate/style.css
  stories/liveEdit/AbbreviateLive.tsx
Labels: new component, typography

#507 feature/code
  .storybook/preview.js
  src/codesnippet/CodeSnippet.tsx
  src/codesnippet/__tests__/CodeSnippet.test.tsx
  src/codesnippet/index.ts
  stories/CodeSnippet/ClassBased.stories.js
  stories/CodeSnippet/Documentation.mdx
  stories/CodeSnippet/Live.stories.js
  stories/CodeSnippet/UnStyled.stories.js
  stories/CodeSnippet/style.css
  stories/liveEdit/CodeSnippetLive.tsx
Labels: new component, typography, Comments to be solved
