Repository Capgemini/dcx-react-library, pull requests merged in 2024-04, with the labels that each got.

#613 fix: adding fileList to onChange for multi file uploads
  example/src/components/MultiUploadDemo.tsx
  package.json
  src/multiUpload/MultiUpload.tsx
  src/multiUpload/__test__/MultiUpload.test.tsx
  stories/MultiUpload/ClassBased.stories.js
  stories/MultiUpload/UnStyled.stories.js
  stories/liveEdit/MultiUploadLive.tsx
Labels: bug

#620 feat: adding css style heading
  src/design-system/heading.css
Labels: bug, design-system

#619 updated the button component to better render aria-label
  package.json
  src/button/Button.tsx
  src/button/__tests__/Button.test.tsx
Labels: a11y

#630 fix: accessbility removing tabIndex
  src/tabGroup/components/Tab.tsx
  src/tabGroup/components/__test__/Tab.test.tsx
Labels: a11y

#622 fix: removing name as default on aria-label
  src/formInput/FormInput.tsx
  src/formInput/__tests__/FormInput.test.tsx
  src/formRadio/FormRadio.tsx
  src/formRadio/__test__/FormRadio.test.tsx
Labels: a11y

#632 fix: removing empty alert / error div for a formInput without an error
  src/common/utils/rolesType.ts
  src/formInput/FormInput.tsx
  src/formInput/__tests__/FormInput.test.tsx
Labels: a11y

#633 Feature/update autocomplete for accessibility
  example/src/components/AutocompleteDemo.tsx
  src/autocomplete/Autocomplete.tsx
  src/autocomplete/ResultList.tsx
  src/autocomplete/__tests__/Autocomplete.test.tsx
  src/autocomplete/__tests__/ResultList.test.tsx
  src/multiSelect/MultiSelect.tsx
  src/multiSelect/__test__/MultiSelect.test.tsx
  stories/Autocomplete/Documentation.mdx
  stories/liveEdit/AutocompleteLive.tsx
Labels: a11y

#641 fix: removing the default 0 tabIndex
  src/autocomplete/Autocomplete.tsx
  src/autocomplete/__tests__/Autocomplete.test.tsx
  src/details/Details.tsx
  src/details/__test__/Details.test.tsx
  src/formDate/Date.tsx
  src/formDate/__test__/FormDate.test.tsx
  src/formInput/FormInput.tsx
  src/formInput/__tests__/FormInput.test.tsx
  src/formSelect/FormSelect.tsx
  src/formSelect/__test__/FormSelect.test.tsx
  src/multiSelect/MultiSelect.tsx
  src/multiSelect/__test__/MultiSelect.test.tsx
  src/progress/Progress.tsx
  src/progress/__tests__/Progress.test.tsx
  src/range/Range.tsx
  src/range/__tests__/Range.test.tsx
  src/table/Table.tsx
  src/table/__tests__/Table.test.tsx
Labels: a11y
